# Flags for the mpileup command
F1=-d 100 --annotate 'INFO/AD,FORMAT/DP,FORMAT/AD,FORMAT/ADF,FORMAT/ADR,FORMAT/SP'
# -d 100: limits the maximum per-BAM depth to 100. This helps to avoid excessive memory usage and maybe bias or something.
# --annotate 'stuff' : adds extra information to the output VCF file.
# INFO/AD: allelic depth. Example idea:reference=A alternate=G and maybe 18 reads support A and 7 support G
# FORMAT/DP: total depth at the position. Is this the sum of AD values?
# FORMAT/AD: allelic depth for each sample?
# FORMAT/ADF(R): allelic depth for forward and reverse strands. No idea what this is for. ChatGPT suggests something called strand bias.
# FORMAT/SP: something about strand bias


# Flags for the call command
F2=--ploidy 1 --annotate 'FORMAT/GQ' 
#--ploidy 1: assumes the organism is haploid.
#--annotate 'FORMAT/GQ': adds "genotype quality" score. 

#-----------Optional Variables and Derivatives-----------------

# GCF Reference genome (I think GCF is kind of the level above NC, but is effectively the same for this single chromosome organism)
GCF = GCF_000013465.1

#Give a more readable name if you have one, else just use the GCF.
REFERENCE_GENOME_READABLE_NAME = $(GCF)

#path to fasta and gff3 files
PATH_TO_REFERENCE_GENOME = $(REFERENCE_GENOME_READABLE_NAME)_dataset/ncbi_dataset/data/$(GCF)

#Reference genome fasta file
REFERENCE_GENOME_FASTA = $(PATH_TO_REFERENCE_GENOME)/*genomic.fna

#SRR number for the aligned reads.
SRR = SRR21835896

#Sample name. Default is the same as the SRR number, but you can change this to something more human-readable if you like.
READABLE_SAMPLE_NAME = $(SRR)

#BAM file
BAM = $(READABLE_SAMPLE_NAME).aligned_reads.bam

VARIANT_CALL_DIRECTORY=variant_calls
#Should not depend on sample name or anything like that, as I want to use this directory for merging.
#Obvious weakness of not being able to analyse different projects in the same place. If I ever need to do this, I'll update this.

VCF = $(VARIANT_CALL_DIRECTORY)/$(READABLE_SAMPLE_NAME).variants.vcf.gz

#----------------End of optional variables and derivatives----------------

usage:
	@echo "variant_calling.mk: call variants given reference genome and bam."
	@echo "THIS ASSUMES A HAPLOID ORGANISM. "
	@echo "#"
	@echo "arguments:"
	@echo "GCF: The GCF accession number for the reference genome. Default is $(GCF)."
	@echo "REFERENCE_GENOME_READABLE_NAME: Optionally provide a more human-readable name for the reference genome. Defaults to GCF."
	@echo "SRR: The SRR accession number for the aligned reads. Default is $(SRR)."
	@echo "READABLE_SAMPLE_NAME: Optionally provide a more human-readable name for the sample. Defaults to SRR."
	@echo "#"
	@echo "targets:"
	@echo "call_variants: Call variants given reference genome and bam."
	@echo "index_variants: Index the VCF file generated by call_variants."
	@echo "merge_vcfs: Merge VCF files made earlier."
	@echo "#"


call_variants:
	@echo "Calling variants for $(READABLE_SAMPLE_NAME) aligned to $(REFERENCE_GENOME_READABLE_NAME)..."

	#make the output directory if it doesn't exist. 
	mkdir -p $(VARIANT_CALL_DIRECTORY)

	#summarise what bases appear at each position. Like the plies in igv.
	bcftools mpileup ${F1} -O u -f ${REFERENCE_GENOME_FASTA} ${BAM} | \
	bcftools call ${F2} -mv -O u | \
	bcftools norm -f ${REFERENCE_GENOME_FASTA} -d all -O u | \
	bcftools sort -O z > ${VCF}

	@echo "Variant calling complete. VCF file generated: ${VCF}"

index_variants:
	@echo "Indexing VCF file..."
	bcftools index ${VCF}
	@echo "Indexing complete. Indexed VCF file: ${VCF}.csi"

merge_vcfs:
	@echo "Merging VCF files in $(VARIANT_CALL_DIRECTORY)..."
	bcftools merge -O z -o multisample.vcf.gz $(VARIANT_CALL_DIRECTORY)/*.vcf.gz
	bcftools index -t multisample.vcf.gz
	@echo "Merging complete. Merged VCF file: multisample.vcf.gz and index: multisample.vcf.gz.tbi in the working directory."

clean:
	@echo "Cleaning up variant call files..."
	rm -rf ${VCF}
	rm -rf ${VCF}.csi
	@echo "Cleanup complete. Removed: ${VCF} and ${VCF}.csi"