#align reads to the reference genome using bowtie2, convert to bam, sort and index bam file, generate bedgraph and bigwig files for coverage visualization in IGV

#GCF accession number for the reference genome you want to align to
GCF = GCF_000013465.1

#Reference genome readable name. This should match the REFERENCE_GENOME_READABLE_NAME in reference_genome.mk. Default is the same as GCF, but you can change this to something more human-readable if you like.
REFERENCE_GENOME_READABLE_NAME = $(GCF)

#reference genome .fai file generated by samtools faidx in reference_genome.mk. This is needed for bedtools genomecov and bedGraphToBigWig.
#At the destination directory, use a wildcard to find the .fai file.
REFERENCE_GENOME_FAI = $(REFERENCE_GENOME_READABLE_NAME)_dataset/ncbi_dataset/data/$(GCF)/*genomic.fna.fai

#SRR number for the reads you want to align
SRR = SRR21835896

#Sample name. Default is the same as the SRR number, but you can change this to something more human-readable if you like.
READABLE_SAMPLE_NAME = $(SRR)

#I wonder if I need to use readable_sample_name any earlier than this to get nice outputs and stuff.

#SAM output file
SAM = $(READABLE_SAMPLE_NAME).aligned_reads.sam

#BAM output file
BAM = $(READABLE_SAMPLE_NAME).aligned_reads.bam

#There's a real argument that this .mk should be split into two, but that doesn't seem crucial for now.

# Temporary bedgraph file
#I have forgotten what this does, give it a more descriptive name.
BEDGRAPH = $(READABLE_SAMPLE_NAME).coverage.bedgraph

#temporary bigwig file
#I have forgotten what this does, give it a more descriptive name.
BIGWIG = $(READABLE_SAMPLE_NAME).coverage.bw

usage:
	@echo "align_reads.mk: Makefile to align reads to a reference genome, convert to bam, sort and index bam file, and generate bedgraph and bigwig files for coverage visualization in IGV."
	@echo "#"
	@echo "arguments:"
	@echo "GCF: The GCF accession number for the reference genome. Default is $(GCF)."
	@echo "REFERENCE_GENOME_READABLE_NAME: --------> MUST MATCH THE REFERENCE_GENOME_READABLE_NAME IN reference_genome.mk <-------- if one was provided and should not be provided if not. "
	@echo "SRR: The SRR accession number for the reads you want to align. Default is $(SRR)."
	@echo "READABLE_SAMPLE_NAME: Optionally provide a more human-readable name for the sample. Defaults to SRR."
	@echo "#"
	@echo "targets:"
	@echo "align: Aligns the reads to the reference genome using bowtie2. Automatically detects if reads are single-end or paired-end based on the presence of _1.fastq and _2.fastq files in the $(SRR).reads directory."
	@echo "bam: Converts the SAM file generated by the align target into a sorted BAM file."
	@echo "bam_index: Indexes the sorted BAM file using samtools."
	@echo "bam_stats: Generates statistics about the BAM file, including flagstat output and average coverage across the genome."
	@echo "bedgraph: Generates a bedgraph file of coverage across the genome using bedtools genomecov."
	@echo "bedgraph_to_bigwig: Converts the bedgraph file to a bigwig file using bedGraphToBigWig for visualization in IGV."
	@echo "#"
	@echo "Future improvements:"
	@echo "Consider splitting this .mk into two, one for alignment and one for coverage visualization, but that doesn't seem crucial for now."
	@echo "It would be nice for the user not to have to worry about the reference genome readable name at all. "
	@echo "If I ever want to align the same reads to two different reference genomes, filenames may collide."
	@echo "#"


align:
	@echo "Aligning reads..."
	if [ -f $(READABLE_SAMPLE_NAME).reads/$(READABLE_SAMPLE_NAME)_2.fastq ]; then \
		echo "Detected paired-end reads"; \
		READ_ARGS="-1 $(READABLE_SAMPLE_NAME).reads/$(READABLE_SAMPLE_NAME)_1.fastq -2 $(READABLE_SAMPLE_NAME).reads/$(READABLE_SAMPLE_NAME)_2.fastq"; \
	elif [ -f $(READABLE_SAMPLE_NAME).reads/$(READABLE_SAMPLE_NAME)_1.fastq ]; then \
		echo "Detected single-end reads"; \
		READ_ARGS="-U $(READABLE_SAMPLE_NAME).reads/$(READABLE_SAMPLE_NAME)_1.fastq"; \
	else \
		echo "Could not determine read layout"; \
		exit 1; \
	fi; \
	bowtie2 -x $(REFERENCE_GENOME_READABLE_NAME)_indices/$(REFERENCE_GENOME_READABLE_NAME)_index $$READ_ARGS > $(SAM)
	@echo "Alignment complete. SAM file generated: $(SAM)"

bam:
	@echo "Converting SAM to BAM and sorting..."
	samtools sort $(SAM) > $(BAM)
	@echo "BAM file generated: $(BAM)"
	
bam_index:
	@echo "Indexing BAM file..."
	samtools index $(BAM)
	@echo "BAM index generated: $(BAM).bai"

bam_stats:
	@echo "Generating BAM statistics..."
	samtools flagstat $(BAM) > $(READABLE_SAMPLE_NAME).bam_stats.txt
	@echo "Stats written to $(READABLE_SAMPLE_NAME).bam_stats.txt"

bedgraph:
	@echo "Generating bedgraph file..."
	LC_ALL=C; bedtools genomecov -ibam  $(BAM) -split -bg | \
    sort -k1,1 -k2,2n > $(BEDGRAPH)
	@echo "Bedgraph file generated: $(READABLE_SAMPLE_NAME).coverage.bedgraph"

bedgraph_to_bigwig:
	@echo "Converting bedgraph to bigwig..."
	bedGraphToBigWig $(BEDGRAPH) $(REFERENCE_GENOME_FAI) $(BIGWIG)
	@echo "BigWig file generated: $(READABLE_SAMPLE_NAME).coverage.bw"

clean:
	@echo "Cleaning up generated files..."
	rm $(SAM) $(BAM) $(BAM).bai $(BEDGRAPH) $(BIGWIG)
	@echo "Cleanup complete."